# Generated by Django 5.1.1 on 2024-12-07 18:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_cita_fecha_alter_cita_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
