# Generated by Django 5.1.1 on 2024-12-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_cita_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
