# Generated by Django 5.1.1 on 2024-12-07 19:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_cita_creado_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='creado_el',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
